e01:
    resource: "@E01Bundle/Controller/"
    type:     annotation
    prefix:   /

e00:
    resource: "@E00Bundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
